// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-vehicles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.75.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false },
    db: { schema: "public" }
  });
}

// src/lib/mcp/tools/search-vehicles.ts
var search_vehicles_default = defineTool({
  name: "search_vehicles",
  title: "Search vehicles",
  description: "Search the Flux marketplace for available vehicles. Filter by make, model, year range, price range, body type, or fuel type. Returns up to 25 non-sold, available listings.",
  inputSchema: {
    make: z.string().trim().optional().describe("Make filter (case-insensitive contains)."),
    model: z.string().trim().optional().describe("Model filter (case-insensitive contains)."),
    body_type: z.string().trim().optional(),
    fuel_type: z.string().trim().optional(),
    min_year: z.number().int().optional(),
    max_year: z.number().int().optional(),
    max_price_kes: z.number().int().optional(),
    limit: z.number().int().min(1).max(25).optional().describe("Max results, default 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    const sb = supabaseForUser(ctx);
    let q = sb.from("vehicles").select(
      "id, make, model, year, price, price_on_request, mileage, body_type, fuel_type, transmission, location, availability_status, photos"
    ).eq("is_sold", false).limit(input.limit ?? 10);
    if (input.make) q = q.ilike("make", `%${input.make}%`);
    if (input.model) q = q.ilike("model", `%${input.model}%`);
    if (input.body_type) q = q.ilike("body_type", `%${input.body_type}%`);
    if (input.fuel_type) q = q.eq("fuel_type", input.fuel_type);
    if (input.min_year) q = q.gte("year", input.min_year);
    if (input.max_year) q = q.lte("year", input.max_year);
    if (input.max_price_kes) q = q.lte("price", input.max_price_kes);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { vehicles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-vehicle.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_vehicle_default = defineTool2({
  name: "get_vehicle",
  title: "Get vehicle details",
  description: "Fetch full details for a single vehicle listing by id, including dealer contact info exposed by RLS.",
  inputSchema: {
    id: z2.string().uuid().describe("The vehicle UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("vehicles").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Vehicle not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { vehicle: data }
    };
  }
});

// src/lib/mcp/tools/list-favorites.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_favorites_default = defineTool3({
  name: "list_my_favorites",
  title: "List my saved vehicles",
  description: "List the signed-in buyer's saved (favorited) vehicles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("favorites").select("id, vehicle_id, created_at, vehicles(id, make, model, year, price, price_on_request, photos)").eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { favorites: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-favorite.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var add_favorite_default = defineTool4({
  name: "add_favorite",
  title: "Save a vehicle",
  description: "Add a vehicle to the signed-in buyer's saved list.",
  inputSchema: { vehicle_id: z3.string().uuid() },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ vehicle_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("favorites").insert({ user_id: ctx.getUserId(), vehicle_id }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: "Saved." }],
      structuredContent: { favorite: data }
    };
  }
});

// src/lib/mcp/tools/remove-favorite.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var remove_favorite_default = defineTool5({
  name: "remove_favorite",
  title: "Unsave a vehicle",
  description: "Remove a vehicle from the signed-in buyer's saved list.",
  inputSchema: { vehicle_id: z4.string().uuid() },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ vehicle_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { error } = await sb.from("favorites").delete().eq("user_id", ctx.getUserId()).eq("vehicle_id", vehicle_id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: "Removed." }] };
  }
});

// src/lib/mcp/tools/list-my-inventory.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_my_inventory_default = defineTool6({
  name: "list_my_inventory",
  title: "List my dealer inventory",
  description: "List all vehicles owned by the signed-in dealer, including sold and unlisted ones. Non-dealers will see an empty list per RLS.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("vehicles").select("id, make, model, year, price, is_sold, availability_status, verification_status, created_at").eq("dealer_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { vehicles: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jrieqgrdiwwroliehlhn";
var mcp_default = defineMcp({
  name: "flux-mcp",
  title: "Flux Marketplace",
  version: "0.1.0",
  instructions: "Tools for Flux \u2014 Kenya's automotive marketplace. Use `search_vehicles` to browse available listings, `get_vehicle` for full details, `list_my_favorites` / `add_favorite` / `remove_favorite` to manage a buyer's saved vehicles, and `list_my_inventory` for a dealer's own listings. All tools act as the signed-in Flux user with RLS applied.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_vehicles_default,
    get_vehicle_default,
    list_favorites_default,
    add_favorite_default,
    remove_favorite_default,
    list_my_inventory_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
