// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzjlnnvwufdydxrjvdtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6amxubnZ3dWZkeWR4cmp2ZHRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5NTY0NDksImV4cCI6MjA3NjUzMjQ0OX0.zmGVQwM3vQmeQVmjyVy3yoID6-_mZicrjcnwik4LiR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});